version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: commissioner
      POSTGRES_USER: big_dog
      POSTGRES_PASSWORD: w00f
    volumes:
      - commissioner_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  commissioner_data: